layout_spectrum: 0.5268528
color:
  saturation: 0.5257788
  lightness: 0.7577873
  brandStrength: 0.8619764
  brandColors:
    - '#91533A'
    - '#302728'
    - '#CFCFCF'
    - '#D8C642'
    - '#88A39B'
  rhythmicContrast: 0.3549946
typography_spectrum: 0.3839957
name: tinygarden
